# API Configuration
API_BASE_URL=http://localhost:3000/api/v1
API_PORT=3000
API_TIMEOUT=30000
API_VERSION=v1

# Database
DATABASE_HOST=database
DATABASE_PORT=5432
DATABASE_NAME=carelink
DATABASE_USER=postgres
DATABASE_PASSWORD=securepassword123
DATABASE_POOL_SIZE=20

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=redispassword
REDIS_MAX_CONNECTIONS=100

# JWT Configuration
JWT_SECRET=your_super_secure_jwt_secret_key_12345
JWT_ACCESS_TOKEN_EXPIRES_IN=7d
JWT_REFRESH_TOKEN_EXPIRES_IN=30d
JWT_TOKEN_TYPE=Bearer

# CORS Configuration
CORS_ALLOWED_ORIGINS=
CORS_ENABLED=true
CORS_CREDENTIALS=true
CORS_MAX_AGE=86400

# Service Configuration
HEALTHCHECK_ENDPOINT=/health
HEALTHCHECK_INTERVAL=30
HEALTHCHECK_TIMEOUT=10

# Feature Flags
FEATURE_NOTIFICATIONS_ENABLED=true
FEATURE_ANALYTICS_ENABLED=true
FEATURE_OFFLINE_SUPPORT=true
FEATURE_SECURITY_LOGS_ENABLED=true

# Monitoring and Logging
LOG_LEVEL=info
LOG_FORMAT=json
LOG_FILE=/var/log/carelink.log

# Frontend Integration
FRONTEND_URL=http://localhost:3000
MOBILE_APP_URL=carelink://

# Development
DEV_MODE=true
DEV_PORT=3000
DEV_HOT_RELOAD=true